fineract-provider/src/main/java/org/apache/fineract/portfolio/loanproduct/serialization/LoanProductDataValidator.java, fineract-provider/src/main/java/org/apache/fineract/portfolio/savings/data/DepositProductDataValidator.java, fineract-provider/src/main/resources/db/changelog/tenant/changelog-tenant.xml, fineract-provider/src/main/resources/db/changelog/tenant/parts/0146_Refactor-short-code-size.xml, fineract-savings/src/main/java/org/apache/fineract/portfolio/savings/data/SavingsProductDataValidator.java
=> CEV-113 Refactor ShortName Param to accomodate 20 characters

fineract-core/src/main/java/org/apache/fineract/portfolio/client/domain/Client.java, fineract-provider/src/main/resources/db/changelog/tenant/parts/0146_Refactor-short-code-size.xml
=> CEV-128 Delete unique constraint on mobile-number on m_client

fineract-core/src/main/java/org/apache/fineract/portfolio/paymentdetail/data/PaymentDetailData.java, fineract-core/src/main/java/org/apache/fineract/portfolio/paymenttype/data/PaymentTypeData.java, fineract-core/src/main/java/org/apache/fineract/portfolio/savings/data/SavingsAccountTransactionData.java, fineract-core/src/main/java/org/apache/fineract/portfolio/savings/data/SavingsAccountTransactionEnumData.java, fineract-core/src/main/java/org/apache/fineract/portfolio/savings/service/SavingsEnumerations.java, fineract-provider/src/main/java/org/apache/fineract/portfolio/savings/api/SavingsAccountTransactionsApiResource.java, fineract-provider/src/main/java/org/apache/fineract/portfolio/savings/data/SavingsAccountDataValidator.java, fineract-provider/src/main/java/org/apache/fineract/portfolio/savings/service/SavingsAccountReadPlatformServiceImpl.java, fineract-savings/src/main/java/org/apache/fineract/portfolio/savings/exception/SavingsAccountTransactionNotFoundException.java, fineract-savings/src/main/java/org/apache/fineract/portfolio/savings/service/SavingsAccountReadPlatformService.java
=> CEV-129 Add Custom API to fetch Savings Account Transaction

fineract-provider/src/main/java/org/apache/fineract/infrastructure/jobs/domain/JobExecutionRepository.java, fineract-provider/src/main/java/org/apache/fineract/portfolio/account/service/StandingInstructionReadPlatformServiceImpl.java, fineract-provider/src/main/java/org/apache/fineract/portfolio/savings/service/SavingsAccountReadPlatformServiceImpl.java, fineract-provider/src/main/java/org/apache/fineract/portfolio/savings/starter/SavingsConfiguration.java
=> CEV-139 Fix Cron Job Execute Standing Instruction

fineract-provider/src/main/java/org/apache/fineract/portfolio/tax/service/TaxReadPlatformServiceImpl.java
https://fiterio.atlassian.net/browse/CEV-132
=> Fix Fetch api for taxes list

fineract-provider/src/main/java/org/apache/fineract/infrastructure/bulkimport/importhandler/ImportHandlerUtils.java, fineract-provider/src/main/java/org/apache/fineract/infrastructure/bulkimport/importhandler/chartofaccounts/ChartOfAccountsImportHandler.java, fineract-provider/src/main/java/org/apache/fineract/infrastructure/bulkimport/populator/chartofaccounts/ChartOfAccountsWorkbook.java
=> Fix Chart of accounts import

fineract-provider/src/main/java/org/apache/fineract/portfolio/savings/service/DepositAccountReadPlatformServiceImpl.java
https://fiterio.atlassian.net/browse/CEV-144
=> CEV-144 Exception on batch job for transferring interest to savings

fineract-provider/src/main/java/org/apache/fineract/portfolio/account/service/AccountTransfersWritePlatformServiceImpl.java, fineract-provider/src/main/java/org/apache/fineract/portfolio/savings/data/SavingsAccountTransactionDataValidator.java, fineract-provider/src/main/java/org/apache/fineract/portfolio/savings/jobs/transferinteresttosavings/TransferInterestToSavingsTasklet.java
=> CEV-144 Exception on batch job for transfering interest to savings

fineract-provider/src/main/java/org/apache/fineract/portfolio/account/service/AccountTransfersWritePlatformService.java, fineract-provider/src/main/java/org/apache/fineract/portfolio/account/service/AccountTransfersWritePlatformServiceImpl.java, fineract-provider/src/main/java/org/apache/fineract/portfolio/savings/domain/DepositAccountDomainService.java, fineract-provider/src/main/java/org/apache/fineract/portfolio/savings/domain/DepositAccountDomainServiceJpa.java, fineract-provider/src/main/java/org/apache/fineract/portfolio/savings/domain/FixedDepositAccount.java, fineract-provider/src/main/java/org/apache/fineract/portfolio/savings/jobs/transferinteresttosavings/TransferInterestToSavingsTasklet.java
=> CEV-149 Fixed Post to Savings Account From FD/RD

fineract-core/src/main/java/org/apache/fineract/commands/service/SynchronousCommandProcessingService.java, fineract-provider/src/main/java/org/apache/fineract/portfolio/savings/domain/DepositAccountDomainServiceJpa.java, fineract-provider/src/main/java/org/apache/fineract/portfolio/savings/service/SavingsAccountWritePlatformServiceJpaRepositoryImpl.java
=> CEV-149 Don't compute more interest beyond the maturity date of any maturity instruction

fineract-core/src/main/java/org/apache/fineract/commands/service/CommandWrapperBuilder.java, fineract-core/src/main/java/org/apache/fineract/portfolio/savings/SavingsApiConstants.java, fineract-provider/src/main/java/org/apache/fineract/portfolio/account/service/MultiTenantTransferServiceImpl.java, fineract-provider/src/main/java/org/apache/fineract/portfolio/savings/api/SavingsAccountTransactionsApiResource.java, fineract-provider/src/main/java/org/apache/fineract/portfolio/savings/handler/DepositSavingsAccountCommandHandler.java, fineract-provider/src/main/java/org/apache/fineract/portfolio/savings/handler/UndoTransactionSavingsAccountWithReferenceCommandHandler.java, fineract-provider/src/main/java/org/apache/fineract/portfolio/savings/handler/WithdrawSavingsAccountCommandHandler.java, fineract-provider/src/main/java/org/apache/fineract/portfolio/savings/service/SavingsAccountWritePlatformServiceJpaRepositoryImpl.java, fineract-provider/src/main/java/org/apache/fineract/portfolio/savings/starter/SavingsConfiguration.java, fineract-savings/src/main/java/org/apache/fineract/portfolio/savings/exception/TransactionUndoNotAllowedException.java, fineract-savings/src/main/java/org/apache/fineract/portfolio/savings/service/SavingsAccountWritePlatformService.java
=> CEV-126 Partial Reversal with Reference Number

fineract-core/src/main/java/org/apache/fineract/portfolio/accountdetails/data/SavingsAccountSummaryData.java, fineract-core/src/main/java/org/apache/fineract/portfolio/savings/data/SavingsAccountData.java, fineract-provider/src/main/java/org/apache/fineract/portfolio/accountdetails/service/AccountDetailsReadPlatformServiceJpaRepositoryImpl.java, fineract-provider/src/main/java/org/apache/fineract/portfolio/savings/service/SavingsAccountReadPlatformServiceImpl.java
=> CEV-115 Add Account Name Parameter

fineract-core/src/main/java/org/apache/fineract/portfolio/savings/data/SavingsAccountTransactionData.java
=> CEV-115 Add Unique Reference to Transactions

fineract-provider/src/main/java/org/apache/fineract/portfolio/savings/service/SavingsAccountReadPlatformServiceImpl.java, fineract-provider/src/main/java/org/apache/fineract/portfolio/savings/service/SavingsAccountWritePlatformServiceJpaRepositoryImpl.java, fineract-savings/src/main/java/org/apache/fineract/portfolio/savings/exception/TransactionUndoNotAllowedException.java
=> CEV-127 Validate Undo Transaction to not re-undo

fineract-provider/src/main/java/org/apache/fineract/portfolio/savings/jobs/postinterestforsavings/PostInterestForSavingTasklet.java, fineract-provider/src/main/java/org/apache/fineract/portfolio/savings/jobs/updatedepositsaccountmaturitydetails/UpdateDepositsAccountMaturityDetailsTasklet.java, fineract-provider/src/main/java/org/apache/fineract/portfolio/savings/service/SavingsAccountInterestPostingServiceImpl.java, fineract-provider/src/main/java/org/apache/fineract/portfolio/savings/service/SavingsAccountWritePlatformServiceJpaRepositoryImpl.java
=> CEV-156 Post Interest when deposit period is daily and compounding is set to annually

fineract-core/src/main/java/org/apache/fineract/portfolio/savings/domain/SavingsHelper.java
=> CEV-156 Fix Fixed Deposit Account Maturity

fineract-provider/src/main/java/org/apache/fineract/portfolio/account/jobs/executestandinginstructions/ExecuteStandingInstructionsTasklet.java
=> CEV-166  Fix Standing Order Instruction

fineract-provider/src/main/java/org/apache/fineract/portfolio/savings/domain/FixedDepositAccount.java, fineract-provider/src/main/java/org/apache/fineract/portfolio/savings/service/DepositAccountWritePlatformServiceJpaRepositoryImpl.java, fineract-savings/src/main/java/org/apache/fineract/portfolio/savings/domain/SavingsAccount.java
=> CEV-172 Fix Re-investment amount

fineract-provider/src/main/java/org/apache/fineract/portfolio/savings/domain/FixedDepositAccount.java, fineract-savings/src/main/java/org/apache/fineract/portfolio/savings/domain/SavingsAccount.java
=> CEV-172 Fix intial Maturity Amount Preview

fineract-provider/src/main/java/org/apache/fineract/portfolio/account/service/AccountTransfersWritePlatformService.java, fineract-provider/src/main/java/org/apache/fineract/portfolio/account/service/AccountTransfersWritePlatformServiceImpl.java, fineract-provider/src/main/java/org/apache/fineract/portfolio/savings/domain/DepositAccountDomainServiceJpa.java, fineract-provider/src/main/java/org/apache/fineract/portfolio/savings/domain/SavingsAccountDomainServiceJpa.java, fineract-provider/src/main/java/org/apache/fineract/portfolio/savings/jobs/transferinteresttosavings/TransferInterestToSavingsTasklet.java, fineract-savings/src/main/java/org/apache/fineract/portfolio/savings/service/SavingsAccountDomainService.java
,Update Deposit Accounts Maturity details
}
=> CEV-172 Disable Interest Posting at {Transfer Interest To Savings

fineract-provider/src/main/java/org/apache/fineract/portfolio/savings/domain/DepositAccountDomainService.java, fineract-provider/src/main/java/org/apache/fineract/portfolio/savings/domain/DepositAccountDomainServiceJpa.java, fineract-provider/src/main/java/org/apache/fineract/portfolio/savings/domain/FixedDepositAccount.java, fineract-provider/src/main/java/org/apache/fineract/portfolio/savings/domain/SavingsAccountDomainServiceJpa.java, fineract-provider/src/main/java/org/apache/fineract/portfolio/savings/service/DepositAccountWritePlatformServiceJpaRepositoryImpl.java, fineract-savings/src/main/java/org/apache/fineract/portfolio/savings/domain/SavingsAccount.java
,Update Deposit Accounts Maturity details
}
=> CEV-172 Disable Interest Posting at {Update Deposit Accounts Maturity details }

fineract-core/src/main/java/org/apache/fineract/portfolio/savings/domain/SavingsHelper.java, fineract-provider/src/main/java/org/apache/fineract/portfolio/savings/domain/FixedDepositAccount.java
https://fiterio.atlassian.net/browse/CEV-174
=> CEV-174 Fix issues for interest posting and maturity date after re invested

fineract-core/src/main/java/org/apache/fineract/portfolio/savings/domain/SavingsHelper.java, fineract-savings/src/main/java/org/apache/fineract/portfolio/savings/domain/DepositAccountTermAndPreClosure.java
=> CEV-174 Fix Interest Posting and Re-Investment

fineract-core/src/main/java/org/apache/fineract/infrastructure/core/config/FineractProperties.java, fineract-core/src/main/java/org/apache/fineract/infrastructure/core/service/tenant/JdbcTenantDetailsService.java, fineract-core/src/main/java/org/apache/fineract/infrastructure/core/service/tenant/ReadOnlyDatabaseConfig.java, fineract-core/src/main/java/org/apache/fineract/infrastructure/core/service/tenant/TenantMapper.java, fineract-provider/src/main/java/org/apache/fineract/infrastructure/security/service/BasicAuthTenantDetailsServiceJdbc.java, fineract-provider/src/main/resources/application.properties
=> Correct db connection handling for readonly cluster

fineract-provider/src/main/resources/application.properties
=> CEV-106 Correct vhost property

fineract-provider/src/main/java/org/apache/fineract/camel/service/CamelAsyncCommandProcessingServiceImpl.java, fineract-provider/src/main/java/org/apache/fineract/infrastructure/security/data/PlatformRequestLog.java, fineract-provider/src/main/java/org/apache/fineract/infrastructure/security/filter/TenantAwareBasicAuthenticationFilter.java, fineract-provider/src/main/java/org/apache/fineract/portfolio/savings/api/AsyncSavingsAccountTransactionsApiResource.java
=> Debug: Add loggin in key places

fineract-provider/src/main/java/org/apache/fineract/camel/service/CamelQueueProcessingService.java
=> Add status and operation to event

fineract-provider/src/main/java/org/apache/fineract/infrastructure/configuration/domain/ConfigurationDomainServiceJpa.java, fineract-provider/src/main/java/org/apache/fineract/portfolio/savings/domain/SavingsAccountAssembler.java, fineract-provider/src/main/java/org/apache/fineract/portfolio/savings/service/SavingsAccountWritePlatformServiceJpaRepositoryImpl.java, fineract-savings/src/main/java/org/apache/fineract/portfolio/savings/domain/SavingsAccount.java, fineract-savings/src/main/java/org/apache/fineract/portfolio/savings/domain/SavingsAccountSummary.java, fineract-savings/src/main/java/org/apache/fineract/portfolio/savings/domain/SavingsAccountTransactionRepository.java
=> Ma01 withdrawal and deposit transaction loading and default transaction fetch on savings account

fineract-core/src/main/java/org/apache/fineract/infrastructure/core/config/FineractProperties.java, fineract-provider/src/main/java/org/apache/fineract/camel/config/CamelRouteBuilder.java, fineract-provider/src/main/java/org/apache/fineract/camel/service/CamelQueueProcessingService.java, fineract-provider/src/main/resources/application.properties
=> Cev 106 manually acknowledge

fineract-provider/src/main/java/org/apache/fineract/portfolio/savings/service/SavingsAccountReadPlatformServiceImpl.java, fineract-savings/src/main/java/org/apache/fineract/portfolio/savings/domain/SavingsAccountTransactionRepository.java
=> Backdated tx transaction fetch query fix

fineract-provider/src/main/java/org/apache/fineract/portfolio/savings/domain/SavingsAccountAssembler.java, fineract-savings/src/main/java/org/apache/fineract/portfolio/savings/domain/SavingsAccountTransactionRepository.java
=> Refactors and more fixes

fineract-provider/src/main/java/org/apache/fineract/portfolio/savings/domain/SavingsAccountAssembler.java, fineract-savings/src/main/java/org/apache/fineract/portfolio/savings/domain/SavingsAccountTransactionRepository.java
=> Last transaction existence check

fineract-core/src/main/java/org/apache/fineract/commands/service/PortfolioCommandSourceWritePlatformServiceImpl.java
=> minor fixes

fineract-core/src/main/java/org/apache/fineract/commands/service/PortfolioCommandSourceWritePlatformServiceImpl.java, fineract-provider/src/main/resources/application.properties
=> minor updates

fineract-core/src/main/java/org/apache/fineract/commands/service/PortfolioCommandSourceWritePlatformServiceImpl.java, fineract-provider/src/main/java/org/apache/fineract/portfolio/savings/service/SavingsAccountReadPlatformServiceImpl.java
=> MA09_optimise_balance_query 

fineract-provider/src/main/java/org/apache/fineract/portfolio/account/service/AccountTransfersWritePlatformServiceImpl.java, fineract-provider/src/main/java/org/apache/fineract/portfolio/savings/domain/DepositAccountAssembler.java, fineract-savings/src/main/java/org/apache/fineract/portfolio/savings/domain/SavingsAccountTransactionRepository.java
=> Running balance fix after transfers

fineract-provider/src/main/java/org/apache/fineract/portfolio/account/service/AccountTransfersWritePlatformServiceImpl.java, fineract-provider/src/main/java/org/apache/fineract/portfolio/savings/domain/DepositAccountDomainServiceJpa.java, fineract-provider/src/main/java/org/apache/fineract/portfolio/savings/domain/SavingsAccountDomainServiceJpa.java
=> regression fix on balances
